In [1]:
import sys
sys.version

'3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'

In [1]:
records = [
('foo', 1, 2),
('bar', 'hello'),
('foo', 3, 4),
]

In [2]:
def do_foo(x, y):
    print('foo', x, y)
def do_bar(s):
    print('bar', s)
for tag, *args in records:
    if tag == 'foo':
        do_foo(*args)
    elif tag == 'bar':
        do_bar(*args)

foo 1 2
bar hello
foo 3 4


In [3]:
print(records)

[('foo', 1, 2), ('bar', 'hello'), ('foo', 3, 4)]


In [4]:
line = 'nobody:*:-2:-2:Unprivileged User:/var/empty:/usr/bin/false'
uname, *fields, homedir, sh = line.split(':')

In [5]:
line

'nobody:*:-2:-2:Unprivileged User:/var/empty:/usr/bin/false'

In [6]:
uname

'nobody'

In [7]:
fields

['*', '-2', '-2', 'Unprivileged User']

In [8]:
homedir

'/var/empty'

In [9]:
sh

'/usr/bin/false'

In [10]:
items = [1, 10, 7, 4, 5, 9]
sum(items)

36

In [11]:
from collections import deque
def search(lines, pattern, history=5):
    previous_lines = deque(maxlen=history)
    for line in lines:
        if pattern in line:
            yield line, previous_lines
        previous_lines.append(line)
# Example use on a file
if __name__ == '__main__':
    with open('somefile.txt') as f:
        for line, prevlines in search(f, 'python', 5):
            for pline in prevlines:
                print(pline, end=',')
            print(line, end='>')
            print('-'*20)

python 1
>--------------------
python 1
,python 2
>--------------------
python 1
,python 2
,python 3
>--------------------
python 1
,python 2
,python 3
,python 4
>--------------------
python 1
,python 2
,python 3
,python 4
,python 5
>--------------------
python 1
,python 2
,python 3
,python 4
,python 5
,python 6
>--------------------
python 2
,python 3
,python 4
,python 5
,python 6
,python 7
>--------------------
python 3
,python 4
,python 5
,python 6
,python 7
,python n
>--------------------


In [12]:
fread=open('somefile.txt')
fprint=fread.read()
print(fprint)

python 1
python 2
python 3
python 4
python 5
python 6
python 7
python n
some
thing
just 
for
test



In [13]:
q=deque(maxlen=3)

In [14]:
q.append(1)

In [15]:
q.append(2)
q.append(3)

In [16]:
q

deque([1, 2, 3])

In [17]:
q.append(4)

In [18]:
q

deque([2, 3, 4])

In [19]:
import heapq
portfolio = [
{'name': 'IBM', 'shares': 100, 'price': 91.1},
{'name': 'AAPL', 'shares': 50, 'price': 543.22},
{'name': 'FB', 'shares': 200, 'price': 21.09},
{'name': 'HPQ', 'shares': 35, 'price': 31.75},
{'name': 'YHOO', 'shares': 45, 'price': 16.35},
{'name': 'ACME', 'shares': 75, 'price': 115.65}
]

In [20]:
cheap=heapq.nsmallest(3,portfolio,key=lambda s:s['price'])

In [21]:
cheap

[{'name': 'YHOO', 'price': 16.35, 'shares': 45},
 {'name': 'FB', 'price': 21.09, 'shares': 200},
 {'name': 'HPQ', 'price': 31.75, 'shares': 35}]

In [22]:
nums=[1,8,2,34,1,42,43,64,234,6,1,4,23,45]
heap=list(nums)


In [23]:
heap

[1, 8, 2, 34, 1, 42, 43, 64, 234, 6, 1, 4, 23, 45]

In [24]:
heapq.heapify(heap)

In [25]:
heap

[1, 1, 2, 34, 1, 4, 43, 64, 234, 6, 8, 42, 23, 45]

In [26]:
heapq.heappop(heap)

1

In [27]:

N=len(nums)
print(N)
print(nums)

14
[1, 8, 2, 34, 1, 42, 43, 64, 234, 6, 1, 4, 23, 45]


In [28]:
sorted(nums,reverse=True)[:]

[234, 64, 45, 43, 42, 34, 23, 8, 6, 4, 2, 1, 1, 1]

In [29]:
sorted(nums)[:]

[1, 1, 1, 2, 4, 6, 8, 23, 34, 42, 43, 45, 64, 234]

In [30]:
2.8**3

21.951999999999995

In [1]:
gamma=1.7
(2-gamma)/(1-gamma)*(4.5**0.3-0.5**0.3)/(4.5**(1-gamma)-0.5**(1-gamma))*0.024

0.006112085776497563

In [4]:
a={1,2,3,1,2,3,4,5}
print(a)
b=[1,2,3,1,2,3,4,5]
print(b)

{1, 2, 3, 4, 5}
[1, 2, 3, 1, 2, 3, 4, 5]


In [10]:
from collections import defaultdict
d = defaultdict(list)
d['a'].append(1)
d['a'].append(2)
d['b'].append(4)

In [11]:
d

defaultdict(list, {'a': [1, 2], 'b': [4]})

In [12]:
e = defaultdict(set)
e['a'].add(1)
e['a'].add(2)
e['b'].add(4)
e

defaultdict(set, {'a': {1, 2}, 'b': {4}})

In [17]:
ls

Applications/          Music/                 randnum.ipynb
CC.py                  Pictures/              randnumpytest.ipynb
Desktop/               Public/                somefile.txt
Documents/             VirtualBox VMs/        x1.txt
Downloads/             advanced python.ipynb  y1.txt
Library/               anaconda2/             z1.txt
Movies/                anaconda3/             z2.txt


In [26]:
from collections import OrderedDict
d = OrderedDict()
d['foo'] = 1
d['bar'] = 2
d['spam'] = 3
d['grok'] = 4
    # Outputs "foo 1", "bar 2", "spam 3", "grok 4"
for key in d: 
    print(key, d[key])


foo 1
bar 2
spam 3
grok 4


In [32]:
import json
json.dumps(d)

'{"foo": 1, "bar": 2, "spam": 3, "grok": 4}'

In [30]:
pairs=[('f',1),('b',2),('r',3)]
d1=defaultdict(list)
for key,value in pairs:
    d1[key].append(value)

In [31]:
d1

defaultdict(list, {'b': [2], 'f': [1], 'r': [3]})

In [36]:
words = [
       'look', 'into', 'my', 'eyes', 'look', 'into', 'my', 'eyes',
       'the', 'eyes', 'the', 'eyes', 'the', 'eyes', 'not', 'around', 'the',
       'eyes', "don't", 'look', 'around', 'the', 'eyes', 'look', 'into',
       'my', 'eyes', "you're", 'under'
]
from collections import Counter 
word_counts = Counter(words)
top_three = word_counts.most_common(3) 
print(top_three)

[('eyes', 8), ('the', 5), ('look', 4)]


In [37]:
morewords = ['why','are','you','not','looking','in','my','eyes']

In [38]:
a = Counter(words)
b = Counter(morewords)

In [40]:
a


Counter({'around': 2,
         "don't": 1,
         'eyes': 8,
         'into': 3,
         'look': 4,
         'my': 3,
         'not': 1,
         'the': 5,
         'under': 1,
         "you're": 1})

In [41]:
b

Counter({'are': 1,
         'eyes': 1,
         'in': 1,
         'looking': 1,
         'my': 1,
         'not': 1,
         'why': 1,
         'you': 1})

In [42]:
c=a+b
c

Counter({'are': 1,
         'around': 2,
         "don't": 1,
         'eyes': 9,
         'in': 1,
         'into': 3,
         'look': 4,
         'looking': 1,
         'my': 4,
         'not': 2,
         'the': 5,
         'under': 1,
         'why': 1,
         'you': 1,
         "you're": 1})

In [43]:
d=a-b
d

Counter({'around': 2,
         "don't": 1,
         'eyes': 7,
         'into': 3,
         'look': 4,
         'my': 2,
         'the': 5,
         'under': 1,
         "you're": 1})

In [44]:
rows = [
        {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003},
        {'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
        {'fname': 'John', 'lname': 'Cleese', 'uid': 1001},
        {'fname': 'Big', 'lname': 'Jones', 'uid': 1004}
]
from operator import itemgetter
rows_by_uid = sorted(rows, key=itemgetter('uid'))
print(rows_by_uid)

[{'fname': 'John', 'lname': 'Cleese', 'uid': 1001}, {'fname': 'David', 'lname': 'Beazley', 'uid': 1002}, {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003}, {'fname': 'Big', 'lname': 'Jones', 'uid': 1004}]


In [46]:
min(rows, key=itemgetter('uid'))
max(rows, key=itemgetter('uid'))

{'fname': 'Big', 'lname': 'Jones', 'uid': 1004}

In [53]:
rows = [
        {'address': '5412 N CLARK', 'date': '07/01/2012'},
        {'address': '5148 N CLARK', 'date': '07/04/2012'},
        {'address': '5800 E 58TH', 'date': '07/02/2012'},
        {'address': '2122 N CLARK', 'date': '07/03/2012'},
        {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'},
        {'address': '1060 W ADDISON', 'date': '07/02/2012'},
        {'address': '4801 N BROADWAY', 'date': '07/01/2012'},
        {'address': '1039 W GRANVILLE', 'date': '07/04/2012'},
]



07/01/2012
 {'address': '5412 N CLARK', 'date': '07/01/2012'}
 {'address': '4801 N BROADWAY', 'date': '07/01/2012'}
07/02/2012
 {'address': '5800 E 58TH', 'date': '07/02/2012'}
 {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'}
 {'address': '1060 W ADDISON', 'date': '07/02/2012'}
07/03/2012
 {'address': '2122 N CLARK', 'date': '07/03/2012'}
07/04/2012
 {'address': '5148 N CLARK', 'date': '07/04/2012'}
 {'address': '1039 W GRANVILLE', 'date': '07/04/2012'}


In [50]:
rows

[{'address': '5412 N CLARK', 'date': '07/01/2012'},
 {'address': '4801 N BROADWAY', 'date': '07/01/2012'},
 {'address': '5800 E 58TH', 'date': '07/02/2012'},
 {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'},
 {'address': '1060 W ADDISON', 'date': '07/02/2012'},
 {'address': '2122 N CLARK', 'date': '07/03/2012'},
 {'address': '5148 N CLARK', 'date': '07/04/2012'},
 {'address': '1039 W GRANVILLE', 'date': '07/04/2012'}]

In [54]:
rows.append({'address': '1040 W GRANVILLE', 'date': '07/04/2012'})

In [55]:
rows

[{'address': '5412 N CLARK', 'date': '07/01/2012'},
 {'address': '4801 N BROADWAY', 'date': '07/01/2012'},
 {'address': '5800 E 58TH', 'date': '07/02/2012'},
 {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'},
 {'address': '1060 W ADDISON', 'date': '07/02/2012'},
 {'address': '2122 N CLARK', 'date': '07/03/2012'},
 {'address': '5148 N CLARK', 'date': '07/04/2012'},
 {'address': '1039 W GRANVILLE', 'date': '07/04/2012'},
 {'address': '1040 W GRANVILLE', 'date': '07/04/2012'}]

In [56]:
from operator import itemgetter 
from itertools import groupby
    # Sort by the desired field first
rows.sort(key=itemgetter('date'))
    # Iterate in groups
for date, items in groupby(rows, key=itemgetter('date')): 
    print(date)
    for i in items: 
        print('', i)

07/01/2012
 {'address': '5412 N CLARK', 'date': '07/01/2012'}
 {'address': '4801 N BROADWAY', 'date': '07/01/2012'}
07/02/2012
 {'address': '5800 E 58TH', 'date': '07/02/2012'}
 {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'}
 {'address': '1060 W ADDISON', 'date': '07/02/2012'}
07/03/2012
 {'address': '2122 N CLARK', 'date': '07/03/2012'}
07/04/2012
 {'address': '5148 N CLARK', 'date': '07/04/2012'}
 {'address': '1039 W GRANVILLE', 'date': '07/04/2012'}
 {'address': '1040 W GRANVILLE', 'date': '07/04/2012'}


In [72]:
mylist = [1, 4, -5, 10, -7, 2, 3, -1,5,-5,6,8,9,-3,7]
a=[n for n in mylist if n>0]

In [73]:
import math
b=[]
for i in a:
    b.append(math.sqrt(i))

AttributeError: 'list' object has no attribute 'leng'

In [139]:
from collections import namedtuple
Subscriber = namedtuple('S', ['name', 'shares','price'])
sub = Subscriber('jonesy@example.com',1,2)
sub1=Subscriber('name1',2,3);
records=(sub,sub1)
def compute_cost(records): 
    total = 0.0
    for rec in records:
        total += rec[1] * rec[2]
    return total
compute_cost(records)

8.0

In [155]:
Stock = namedtuple('Stock', ['name', 'shares', 'price'])
a=[0,1,2,3,4,5]

for i in a:
    b[i]=Stock('name%s'% i,i,i)
    print(b[i])

Stock(name='name0', shares=0, price=0)
Stock(name='name1', shares=1, price=1)
Stock(name='name2', shares=2, price=2)
Stock(name='name3', shares=3, price=3)
Stock(name='name4', shares=4, price=4)
Stock(name='name5', shares=5, price=5)


In [179]:
def compute_cost1(records): 
    total = 0.0
    for rec in records: 
        s = Stock(*rec)
        total += s.shares * s.price 
    return total
record=(b[0],b[1],b[2],b[3],b[4])
record
compute_cost1(record)

30.0

In [2]:
pwd

'/Users/brettlv'

Subscriber

In [33]:
# Determine if any .py files exist in a directory
import os,sys
files = os.listdir('.')
if any(name.endswith('.py') for name in files):
    print('There be python!') 
    
else:
    print('Sorry, no python.')

There be python!


In [18]:
s = ('ACME', 50, 123.45) 
print(','.join(str(x) for x in s))
print(s)

ACME,50,123.45
('ACME', 50, 123.45)


In [37]:
filenames=os.listdir('.')
[name for name in filenames if name.endswith(('.py','.txt'))]

['CC.py', 'somefile.txt', 'x1.txt', 'y1.txt', 'z1.txt', 'z2.txt']

In [26]:
line = 'asdf fjdk; afed, fjek,asdf, foo'
import re
re.split(r'[;,\s]\s*',line)

['asdf', 'fjdk', 'afed', 'fjek', 'asdf', 'foo']

In [31]:
re.split(r'[;,\s]\s*',line)[:3]

['asdf', 'fjdk', 'afed']

In [28]:
re.split(r'[;,\s]\s*',line)[1::2]

['fjdk', 'fjek', 'foo']

In [70]:
from urllib.request import urlopen

def read_data(name):
    if name.startswith(('http:', 'https:', 'ftp:')):
        return urlopen(name).read() 
    else:
        with open(name) as f: 
            return f.read()
        
url1 = 'http://www.zhihu.com'
other='somefile.txt'
#read_data(url)
read_data(other)
        

'python 1\npython 2\npython 3\npython 4\npython 5\npython 6\npython 7\npython n\nsome\nthing\njust \nfor\ntest\n'

In [69]:
choices = ['http:', 'ftp:']
url = 'http://www.python.org'
url.startswith(tuple(choices))

True

In [71]:
filename='spam.txt'
filename[-4:]=='.txt'

True

In [72]:
from fnmatch import fnmatch, fnmatchcase
fnmatch('foo.txt', '*.txt')


True

In [73]:
fnmatch('foo.txt', '*.TXT')

False

In [74]:
text = 'yeah, but no, but yeah, but no, but yeah'
text.find('no')

10

In [82]:
datepat = re.compile(r'(\d+)/(\d+)/(\d+)')
text = 'Today is 11/27/2012. PyCon starts 3/13/2013.' 
datepat.findall(text)

[('11', '27', '2012'), ('3', '13', '2013')]

In [83]:
for month, day, year in datepat.findall(text): 
    print('{}-{}-{}'.format(year, month, day))

2012-11-27
2013-3-13


In [84]:
for m in datepat.finditer(text):
    print(m.groups(0))

('11', '27', '2012')
('3', '13', '2013')


In [90]:
from calendar import month_abbr
def change_date(m):
    mon_name = month_abbr[int(m.group(1))]
    return '{} {} {}'.format(m.group(2), mon_name, m.group(3))

In [91]:
import re
datepat = re.compile(r'(\d+)/(\d+)/(\d+)')
datepat.sub(change_date, text)

'Today is 27 Nov 2012. PyCon starts 13 Mar 2013.'

In [88]:
datepat.sub(r'\3-\1-\2', text)

'Today is 2012-11-27. PyCon starts 2013-3-13.'

In [99]:
for i in range(12):
    print(month_abbr[i])


Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov


In [100]:
text = 'UPPER PYTHON, lower python, Mixed Python' 
re.findall('python', text, flags=re.IGNORECASE)

['PYTHON', 'python', 'Python']

In [111]:
comment = re.compile(r'/\*((?:.|\n)*?)\*/') 
text2 = '''/* this is a
... multiline comment */ 
... '''



comment.findall(text2)

[' this is a\n... multiline comment ']

In [112]:
comment = re.compile(r'/\*(.*?)\*/', re.DOTALL)
comment.findall(text2)

[' this is a\n... multiline comment ']

In [113]:
s='\ufb01'
s

'fi'

In [115]:
import unicodedata
unicodedata.normalize('NFKD',s)

'fi'

In [116]:
s = ' hello world \n'
re.sub('\s+', ' ', s)

' hello world '

In [120]:
filename

'spam.txt'

In [121]:
with open(filename) as f:
    lines = (line.strip() for line in f)
    for line in lines:
        print(line)

spam
txt
test


In [133]:
x=1.2345678
format(x,'^20.3f')


'       1.235        '

In [138]:
a='hello'+' '+ 'world'
a

'hello world'

In [140]:
print('a', 'b', 'c', sep=':')

a:b:c


In [145]:
filename

'spam.txt'

In [174]:
def sample(): 
    yield 'Is'
    yield 'Chicago' 
    yield 'Not' 
    yield 'Chicago?'


def combine(source, maxsize): 
    parts = []
    size = 0
    for part in source:
        parts.append(part) 
        size += len(part) 
        if size > maxsize:
            yield ''.join(parts) 
            parts = []
            size = 0
    yield ''.join(parts)
    
with open(filename,'a+') as f:    
    for part in combine(sample(), 32768):
        f.write(part+'\t')
f.close()

In [163]:
3+4*5


23

In [161]:
PRINT = r'(P<PRINT>print)'
NAME  = r'(P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)'
WS = r'(?P<WS>\s+)'

from collections import namedtuple
import re

Token = namedtuple('Token', ['type','value'])
def generate_tokens(pat, text):
    scanner = pat.scanner(text)
    for m in iter(scanner.match, None):
        yield Token(m.lastgroup, m.group())
        




In [162]:
master_pat = re.compile('|'.join([PRINT, NAME])) 
for tok in generate_tokens(master_pat, 'printer'):
    print(tok)

In [175]:
with open('jalape\xf1o.txt', 'w') as f: 
    f.write('spicy')

In [181]:
round(2.5)

2

In [184]:
a=2.1
b=4.2
c=a+b
c
d=1242363
round(d,-2)

1242400

In [193]:
from decimal import Decimal
from decimal import localcontext
a = Decimal('2.2')
b=Decimal('0.3')

with localcontext() as ctx:
    ctx.prec=50
    print(a/b)

7.3333333333333333333333333333333333333333333333333


In [198]:
import math
nums = [1.23e+18, 1, -1.23e+18]
math.fsum(nums)
sum(nums)

0.0

In [202]:
x=1234
print(bin(x))
print(oct(x))
print(hex(x))

0b10011010010
0o2322
0x4d2


In [206]:
a=complex(2,4)
b=2-3j

In [211]:
import cmath
cmath.sqrt(-1)

1j

In [215]:
a=float('inf')
b=-a
c=float('NaN')

In [216]:
c

nan

In [218]:
1/c

nan

In [222]:
from fractions import Fraction
x=Fraction(3,7)
y=Fraction(9,5)
print(x+y)

78/35


In [223]:
float(x+y)

2.2285714285714286

In [228]:

import numpy as np
a=np.arange(3)
b=np.arange(3)+1

In [230]:
a

array([0, 1, 2])

In [231]:
b

array([1, 2, 3])

In [241]:
m=np.matrix([[1,6,8],[2,4,7],[3,5,9]])

In [242]:
import numpy.linalg
numpy.linalg.det(m)

3.0000000000000018

In [276]:
ei=np.linalg.eigvals(m)
ei

array([ 15.43767325,  -1.28663614,  -0.15103711])

In [283]:
for eii in ei:
    print(numpy.linalg.det(eii*np.matrix([[1,0,0],[0,1,0],[0,0,1]])-m))

4.28240896373e-12
-1.85699365923e-14
-1.05020166599e-14


In [269]:
n=np.matrix([[1,2],[2,5]])
np.linalg.det(n)

1.0

In [296]:
ein,eiv=np.linalg.eigh(n)
ein

array([ 0.17157288,  5.82842712])

In [297]:
eiv

matrix([[-0.92387953,  0.38268343],
        [ 0.38268343,  0.92387953]])

In [274]:
np.shape(ein)

(2,)

% advance.py

In [385]:
%run advance.py

9


In [287]:
x=np.diag((1,2,3))
a,b=np.linalg.eig(x)

In [288]:
a

array([ 1.,  2.,  3.])

In [289]:
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [298]:
v=np.matrix([[2],[3],[4]])

In [299]:
x=np.linalg.solve(m,v)

In [301]:
v

matrix([[2],
        [3],
        [4]])

In [386]:
import random
for i in range(3):
    print(random.gauss(0,1))

0.40516102743583265
-0.2313687910721352
1.6759321038678394


In [311]:
from datetime import datetime
from datetime import timedelta

now=datetime.today()

In [312]:
now

datetime.datetime(2017, 5, 16, 10, 32, 12, 421123)

In [315]:
a=datetime(2017,5,31)

In [316]:
(a-now).days

14

In [317]:
now

datetime.datetime(2017, 5, 16, 10, 32, 12, 421123)

In [334]:
from pytz import timezone 
import pytz
d=datetime(2017,5,16,10,32,12)
central=timezone('Asia/Shanghai')
loc_now=central.localize(d)
utc_now=loc_now.astimezone(pytz.utc)
utc_now

datetime.datetime(2017, 5, 16, 2, 32, 12, tzinfo=<UTC>)

In [336]:
print(loc_now)
print(utc_now)

2017-05-16 10:32:12+08:00
2017-05-16 02:32:12+00:00


In [340]:
with ope
n('somefile.txt','rt') as f:    data=f.read()
data

'python 1\npython 2\npython 3\npython 4\npython 5\npython 6\npython 7\npython n\nsome\nthing\njust \nfor\ntest\n'

In [339]:
print(data)

python 1
python 2
python 3
python 4
python 5
python 6
python 7
python n
some
thing
just 
for
test



In [362]:
with open('somefile4.txt','xt') as f:    
    print('hello world',file=f)

In [363]:
with open('somefile4.txt','rt') as f:    
    print(f.read())

hello world



In [7]:
pwd

'/Users/brettlv'

In [14]:
pwd='/Users/brettlv'
pwd_path=os.getcwd()
print(os.path.abspath(pwd_path))
print(pwd)
os.chdir(pwd)#改变当前工作目录
print(os.path.abspath(os.getcwd()))
os.chdir(pwd_path)
print(os.path.abspath(os.getcwd()))

/Users/brettlv/blog/brettlv.github.io/pythoncode
/Users/brettlv
/Users/brettlv
/Users/brettlv/blog/brettlv.github.io/pythoncode


In [15]:
pwd

'/Users/brettlv'

In [3]:
import os 
path='/Users/brettlv/somefile.txt'
os.path.basename(path)
#

'somefile.txt'

In [4]:
os.path.dirname(path)

'/Users/brettlv'

In [20]:
import os
import os.path
import glob

names=[name for name in os.listdir(pwd) if os.path.isdir(os.path.join(pwd,name))]
print(names)

['.aladin', '.anaconda', '.astropy', '.bash_sessions', '.cache', '.casa', '.conda', '.config', '.continuum', '.cups', '.gag', '.gem', '.idlerc', '.ipynb_checkpoints', '.ipython', '.ipython-ciao', '.jupyter', '.keras', '.macports', '.matlab', '.matplotlib', '.node-gyp', '.npm', '.oracle_jre_usage', '.qt', '.sas.d', '.skycat', '.ssh', '.stack', '.subversion', '.Trash', '.vim', '.vnc', '.xspec', '16th_synthesis_imaging_workshop', 'adam', 'AIPS', 'AmericanVideo', 'anaconda2', 'anaconda3', 'Applications', 'ArXiv', 'bayes', 'blog', 'casa', 'CIAO', 'cxcds_param4', 'Desktop', 'Documents', 'Downloads', 'fvtmp', 'gif', 'GW170817_pdf_download', 'html', 'jupyter-tutorial-adass17', 'Library', 'Movies', 'Music', 'node_modules', 'pfiles', 'Pictures', 'Public', 'pycbc', 'SAS', 'saved_state', 'scrapytutorial', 'src_heasoft', 'url', 'VirtualBox VMs', 'wcstools', 'xpa', 'youngradiosource', 'Zotero']


In [21]:
pyfiles = [name for name in os.listdir(pwd) if name.endswith('.py')]
print(pyfiles)

['get-pip.py']


In [22]:
# Get file sizes and modification dates
name_sz_date = [(name, os.path.getsize(name), os.path.getmtime(name)) for name in pyfiles]
for name, size, mtime in name_sz_date: 
    print(name, size, mtime)

FileNotFoundError: [Errno 2] No such file or directory: 'get-pip.py'

%run 
'Ctrl-C'


In [389]:
import csv


In [402]:
url

'http://www.python.org'

In [404]:
from urllib.request import urlopen
import json
import pandas
url
response=urlopen(url)
html=response.read()

In [406]:
response

In [392]:
 _no_value = object()
def spam(a, b=_no_value): 
    if b is _no_value:
        print('No b value supplied')

In [393]:
spam(1)

No b value supplied


In [396]:
def urltemplate(template): 
    def opener(**kwargs):
        return urlopen(template.format_map(kwargs)) 
    return opener
# Example use
yahoo = urltemplate('http://finance.yahoo.com/d/quotes.csv?s={names}&f={fields}') 
for line in yahoo(names='IBM,AAPL,FB', fields='sl1c1v'):
    print(line.decode('utf-8'))

URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

In [19]:
ls

Applications/          Pictures/              randnumpytest.ipynb
CC.ipynb               Public/                redshiftYRS
CC.py                  VirtualBox VMs/        somefile.txt
Desktop/               advanced python.ipynb  x1.txt
Documents/             anaconda2/             y1.txt
Downloads/             anaconda3/             z1.txt
Library/               astro.ipynb            z2.txt
Movies/                datatest
Music/                 randnum.ipynb


In [407]:
%load_ext Cython

In [409]:
%%cython
cdef float a,b
def plusa(float a,float b):
    return (a+b)

In [410]:
plusa(1,2)

3.0

In [413]:
def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
fib(100)

0 1 1 2 3 5 8 13 21 34 55 89 

In [424]:
import time
from functools import wraps
def timethis(func): 
    '''
    Decorator that reports the execution time.  
    '''
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs) 
        end = time.time() 
        print(func.__name__, end-start) 
        return result
    return wrapper


In [427]:
@timethis  
def countdown(n):
    '''
    Counts down
    '''
    while n>0:
        n -= 1

In [431]:
for i in range(10):
    countdown(10**i)


countdown 9.5367431640625e-07
countdown 2.1457672119140625e-06
countdown 6.9141387939453125e-06
countdown 0.00011992454528808594
countdown 0.0010139942169189453
countdown 0.008364200592041016
countdown 0.06273603439331055
countdown 0.6473579406738281
countdown 6.055685043334961
countdown 60.3550341129303


In [438]:
@timethis  
def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=',')
        a, b = b, a+b
fib(10**1)



0,1,1,2,3,5,8,fib 0.0008800029754638672


In [451]:
start=time.time()
#fib0=fib.__wrapped__
#fib0(10**1)
fib(10**1)
end=time.time()
print(end-start)

0,1,1,2,3,5,8,fib 0.0005867481231689453
0.0007529258728027344


In [453]:
ls

Applications/          VirtualBox VMs/        redshiftYRS
CC.ipynb               advance.py             somefile.txt
CC.py                  advanced python.ipynb  somefile1.txt
Desktop/               anaconda2/             somefile2.txt
Documents/             anaconda3/             somefile3.txt
Downloads/             astro.ipynb            somefile4.txt
Library/               datatest               spam.txt
Movies/                jalapeño.txt           x1.txt
Music/                 plusab.pyx             y1.txt
Pictures/              randnum.ipynb          z1.txt
Public/                randnumpytest.ipynb    z2.txt


In [462]:
import advance
advance.advance(1,2,3)

9

In [465]:
import mymodule
from mymodule import A,B

In [469]:
A.spam('s')
B.bar('s')

A.spam
B.bar


In [ ]:
%run filein.py /etc/passwd

In [474]:
user=input('enter your name')
age=input('enter your age,only int permitted')
height=input('enter your height, cm')

enter your namebrett
enter your age,only int permitted23
enter your height, cm72


In [475]:
user

'brett'

In [478]:
import os
sz=os.get_terminal_size()
sz

os.terminal_size(columns=80, lines=24)

In [481]:
ls *.py > py.txt

In [483]:
more py.txt

'/Users/brettlv'

In [485]:
import webbrowser
webbrowser.open('www.zhihu.com')

True